name: Lint, Package, Scan and Push Helm Charts to GAR

on:
  push:

env:
  PROJECT_ID: fine-effect-382702
  GAR_LOCATION: us-central1
  REPOSITORY: helm-charts-repo
  CHART_NAME: helm_charts
  VERSION_PREFIX: 0.1.0
  VERSION_SUFFIX: -sha
  #CHART_VERSION: ${{ env.VERSION_PREFIX }}-${{ env.GITHUB_SHA }}-sha

jobs:
  lint-package-push-chart:
    name: Helm Charts lint, package and push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: "v3.8.1"

      - name: Lint Helm Chart
        run: helm lint $CHART_NAME

      - name: Set Chart Version
        id: set-chart-version
        run: |
          echo "CHART_VERSION=$VERSION_PREFIX-${GITHUB_SHA}$VERSION_SUFFIX" >> $GITHUB_ENV

      - name: Package Helm Chart
        run: helm package $CHART_NAME --version $CHART_VERSION --destination .

      - name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v0.6.0"
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY_PROJ }}"
          token_format: "access_token"

      - name: Push Helm Chart to GAR
        run: |
          #helm push $CHART_NAME-$CHART_VERSION.tgz oci://us-central1-docker.pkg.dev/$PROJECT_ID/$REPOSITORY
          export CHART_PACKAGE="$CHART_NAME-$CHART_VERSION.tgz"
          export GAR_REGISTRY="$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY"
          #export GAR_PATH="${env.PROJECT_ID}/${env.REPOSITORY}/${CHART_PACKAGE}"
          helm push $CHART_PACKAGE "oci://${GAR_REGISTRY}" --username=_json_key --password="$(cat fine-effect-382702-8bacbd700986.json)"
