name: Lint, Package, Scan and Push Helm Charts to GAR

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: fine-effect-382702
  GAR_LOCATION: us-central1
  REPOSITORY: helm-charts-repo

jobs:
  lint-package-push-chart:
    name: Helm Charts lint, package, and push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: "v3.8.1"

      - name: Lint Helm Chart
        run: helm lint ${{ env.CHART_NAME }}

      - name: Set Chart Version
        id: set-chart-version
        run: |
          echo "CHART_VERSION=${{ env.VERSION_PREFIX }}-${{ github.sha }}" >> $GITHUB_ENV

      - name: Package Helm Chart
        run: helm package ${{ env.CHART_NAME }} --version ${{ env.CHART_VERSION }} --destination .

      - name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v0.6.0"
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY_PROJ }}"
          token_format: "access_token"

      - name: Push Helm Chart to GAR
        run: |
          CHART_PACKAGE="${{ env.CHART_NAME }}-${{ env.VERSION_PREFIX }}-${{ github.sha }}.tgz"
          GAR_REGISTRY="${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}"
          helm push ${{ env.CHART_PACKAGE }} "oci://${{ env.GAR_REGISTRY }}" --username=_json_key --password="$(cat ${{ secrets.GCP_SA_KEY_PROJ }})"
